version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
      POSTGRES_DB: stockdb
    ports:
      - "5432:5432"

  collector:
    build: ./apps/collector
    depends_on:
      - redis

  candle-builder:
    build: ./apps/candle-builder
    depends_on:
      - redis

  api:
    build: ./apps/api
    ports:
      - "3000:3000"
    depends_on:
      - redis

  web:
    build: ./apps/web
    ports:
      - "4321:4321"
    depends_on:
      - api